eyebleach/models.py
from datetime import datetime
from eyebleach import mongo

class User:
    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.password = password
        self.register_date = datetime.utcnow()

    def register(self):
        # Insert user into MongoDB
        pass

eyebleach/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])

    password = PasswordField('Password', validators=[DataRequired(), Length(min=6)])

    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])

    submit = SubmitField('Sign Up')

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])

    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')

eyebleach/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from eyebleach import mongo

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])

    password = PasswordField('Password', validators=[DataRequired(), Length(min=6)])

    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])

    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        if mongo.db.users.find_one({ "username": username.data }):
            raise ValidationError('That username is already taken. Please choose a different one.')

    def validate_email(self, email):
        if mongo.db.users.find_one({ "email": email.data }):
            raise ValidationError('That email is already taken. Please choose a different one.')

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])

    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')

eyebleach/__init__.py
from flask import Flask
from flask_pymongo import PyMongo
from flask_bcrypt import Bcrypt
from eyebleach.config import Config

mongo = PyMongo()
bcrypt = Bcrypt()

def create_app(config=Config):

    app = Flask(__name__)
    app.config.from_object(Config)

    mongo.init_app(app)
    print(app.config)
    mongo.cx.server_info()

    bcrypt.init_app(app)

    # Routes
    from eyebleach.main.routes import main  # noqa: E402, F401
    from eyebleach.user.routes import user  # noqa: E402, F401

    app.register_blueprint(main)
    app.register_blueprint(user)

    return app

eyebleach/main/routes.py
from flask import render_template, Blueprint
import requests

main = Blueprint('main', __name__)

# Home route
@main.route('/')
@main.route('/home')
def home():
    res = requests.get('https://random.dog/woof.json')
    image_url = res.json()['url']
    return render_template('index.html', image=image_url)

# About route
@main.route('/about')
def about():
    return render_template('about.html', title='About')

eyebleach/user/routes.py
from flask import render_template, url_for, flash, redirect, Blueprint
from eyebleach.user.forms import RegistrationForm, LoginForm
from eyebleach.models import User
from eyebleach import bcrypt

user = Blueprint('user', __name__)

# Registration route
@user.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(form.username.data, form.email.data, hashed_password)
        user.register()
        flash(f'Account created for {form.username.data}!', 'success')
        return redirect(url_for('main.home'))
    return render_template('register.html', form=form)

# Login route
@user.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    return render_template('login.html', form=form)

eyebleach/templates/about.html
{% extends "layout.html" %}
{% block content %}

{% endblock content %}

eyebleach/templates/index.html
{% extends "layout.html" %}
{% block content %}
    <img src={{ image }} alt='Not Found'>
{% endblock content %}

eyebleach/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Eyebleach - {{ title }} </title>
    {% else %}
        <title>Bleach for Your Eyes</title>
    {% endif %}
</head>
<body>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-md bg-light">
        <div class="container">
            <a class="navbar-brand mr-4" href="/">Eyebleach</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                    <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{{ url_for('user.login') }}">Login</a>
                    <a class="nav-item nav-link" href="{{ url_for('user.register') }}">Register</a>
                </div>
            </div>
        </div>
    </nav>

    <div class="container">
        <!-- Flashed messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {% block content %}{% endblock %}
    </div>

     <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
     <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

eyebleach/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-4 mx-auto">

            <h3 class="text-center mt-4">Join Eyebleach!</h3>
    
            <form class="border border-light p-5" method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <div class="field mb-4">
                        {% if form.username.errors %}
                            {{ form.username(placeholder="Username", class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(placeholder="Username", class="form-control") }}
                        {% endif %}
                    </div>
                    <div class="field mb-4">
                        {% if form.email.errors %}
                            {{ form.email(placeholder="Email", class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(placeholder="Email", class="form-control") }}
                        {% endif %}
                    </div>
                    <div class="field mb-4">
                        {% if form.password.errors %}
                            {{ form.password(placeholder="Password", class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(placeholder="Password", class="form-control") }}
                        {% endif %}
                    </div>
                    <div class="form-check">
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember.label(class="form-check")}}
                    </div>

                </fieldset>
                <div class="field text-center">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
                <small class="text-muted">
                    <a href="#">Forgot Password?</a>
                </small>
            </form>
    
            <div class="border-top pt-3">
                <small class="text-muted">
                    Need an account? Click <a href="{{ url_for('user.login')}}">here</a> to sign up!
                </small>
            </div>
        </div>
    </div>
{% endblock content %}

eyebleach/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="row">
        <div class="col-md-4 mx-auto">

            <h3 class="text-center mt-4">Join Eyebleach!</h3>
    
            <form class="border border-light p-5" method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <div class="field mb-4">
                        {% if form.username.errors %}
                            {{ form.username(placeholder="Username", class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(placeholder="Username", class="form-control") }}
                        {% endif %}
                    </div>
                    <div class="field mb-4">
                        {% if form.email.errors %}
                            {{ form.email(placeholder="Email", class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(placeholder="Email", class="form-control") }}
                        {% endif %}
                    </div>
                    <div class="field mb-4">
                        {% if form.password.errors %}
                            {{ form.password(placeholder="Password", class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(placeholder="Password", class="form-control") }}
                        {% endif %}
                    </div>
                    <div class="field mb-4">
                        {% if form.confirm_password.errors %}
                            {{ form.confirm_password(placeholder="Confirm Password", class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.confirm_password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.confirm_password(placeholder="Confirm Password", class="form-control") }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="field text-center">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
    
            <div class="border-top pt-3">
                <small class="text-muted">
                    Already joined? Click <a href="{{ url_for('user.login')}}">here</a> to sign in!
                </small>
            </div>
        </div>
    </div>
{% endblock content %}